### ISSUE TITLE
Problem when running calibrate.launch

### ISSUE THREAD

**Issue by ybwang99** [ethz-asl/COIN-LIO#1]
Thanks for this great work in the SLAM LIO research field!

Today I would like to run COIN-LIO with my Ouster 32 data. And when I run the calibrate.launch, I meet the problem that the procedure stops at the place illustrated in the figure. I think it might be the shared_ptr problem, could you help solve this issue?
![calibration](https://github.com/ethz-asl/COIN-LIO/assets/91960557/47bfe88c-1268-4f2f-82ee-488b307289a8)

**Comment by patripfr** [comment]
Hi!
Could you specify a bit more what happens exactly? Does the code crash or does nothing happen at all? 
A screenshot of the command that you execute and the terminal output would be helpful to investigate :)
FYI: I haven't tested with 32 beam lidars so far, and I'm not sure if the photometric part will work well given the low resolution image.

**Comment by RuanJY** [comment]
I also tested my bag with an Ouster OS1-32 Lidar.

I modified the `params.yaml` file:

    scan_line: 32

and use this command:

```
roslaunch coin_lio mapping.launch bag_file:=my.bag metadata_file:=/root/data/metadata.json point_topic:=/ouster/points imu_topic:=/ouster/imu column_shift:=-0
```

I used the metadata of Ouster OS1-32 Lidar and conducted the calibration process.

and I got the error:
```
[ INFO] [1714228008.902486066]: IMU Initial Done
[ WARN] [1714228008.903411994]: No point, skip this scan!

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/core/src/matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

[laserMapping-1] process has died 
```
I echo the width and height of the ouster point cloud; they are 1024 and 32.

Is there some hard-coded height of the image?

**Comment by patripfr** [comment]
Hi @RuanJY,
The image height is not hard coded.
I think the issue appears because the default parameters were designed for a 128 beam lidar and the mask is larger than 32 rows.
We use this [mask](https://github.com/ethz-asl/COIN-LIO/blob/3db8b9507e56ad8768a2a37959677a309c836396/config/params.yaml#L55) to block out the area that is covered by the ouster connector (visible for os0). I think you can simply remove this line for a 32 beam os1.

Additionally you should probably adjust the [window size](https://github.com/ethz-asl/COIN-LIO/blob/main/config/params.yaml#L54) to something less high such as [41, 5] or [41,3].

I'm also not sure how the line removal filter will work for a 32 beam lidar, as it is a 2D filter with more than 32 entries. Alternatively you can deactivate it by setting [this parameter](https://github.com/ethz-asl/COIN-LIO/blob/main/src/image_processing.cpp#L37) to false in the launch file.

Cheers,
Patrick

**Comment by RuanJY** [comment]
Thanks for your kind help and fast response; 

now I can run it with OS1-32 after change the [mask](https://github.com/ethz-asl/COIN-LIO/blob/3db8b9507e56ad8768a2a37959677a309c836396/config/params.yaml#L55)

**Comment by ybwang99** [comment]
> Hi! Could you specify a bit more what happens exactly? Does the code crash or does nothing happen at all? A screenshot of the command that you execute and the terminal output would be helpful to investigate :) FYI: I haven't tested with 32 beam lidars so far, and I'm not sure if the photometric part will work well given the low resolution image.

Sorry, I forgot to add the metadata_file in my command. It works normally now after correcting this mistake. Thx for your kind help and quick response!

**Comment by patripfr** [comment]
@RuanJY I realized that you should also change the [margin parameter](https://github.com/ethz-asl/COIN-LIO/blob/3db8b9507e56ad8768a2a37959677a309c836396/config/params.yaml#L52). Features that are closer than the margin size to the image boarder are rejected, so if the default value of 10 is used for a 32 beam lidar only 12 beams remain in the allowed range. Therefore, a smaller value like 3 or 4 would probably make more sense.

**Comment by AFEICHINA** [comment]
Hello, @ybwang99 and @RuanJY. I currently do not have an Ouster LiDAR unit. However, I am very interested in the mapping results produced by the Ouster 32-wire LiDAR. Would it be possible for you to share some of the mapping results you've obtained with the Ouster 32-wire LiDAR?

**Comment by satyajitghana** [comment]
I have a OS0-16 line lidar, would COIN-LIO work?

**Comment by RuanJY** [comment]
> Hello, @ybwang99 and @RuanJY. I currently do not have an Ouster LiDAR unit. However, I am very interested in the mapping results produced by the Ouster 32-wire LiDAR. Would it be possible for you to share some of the mapping results you've obtained with the Ouster 32-wire LiDAR?

Here is a map built by coin-lio using os1-21 lidar.

![image](https://github.com/ethz-asl/COIN-LIO/assets/24611620/7b6958a6-36bf-4223-b4d0-4b3f289593f8)

**Comment by RuanJY** [comment]
> @RuanJY I realized that you should also change the [margin parameter](https://github.com/ethz-asl/COIN-LIO/blob/3db8b9507e56ad8768a2a37959677a309c836396/config/params.yaml#L52). Features that are closer than the margin size to the image boarder are rejected, so if the default value of 10 is used for a 32 beam lidar only 12 beams remain in the allowed range. Therefore, a smaller value like 3 or 4 would probably make more sense.

Great. The number of features increased after doing so.
![image](https://github.com/ethz-asl/COIN-LIO/assets/24611620/cde08a0c-4e54-4592-bbc0-c0cba84f1b9c)
