### ISSUE TITLE
Details about metadata file

### ISSUE THREAD

**Issue by kousheekc-lynxdrone** [ethz-asl/COIN-LIO#13]
Hello,

Thank you so much for this amazing project. I wanted to test this out with my own data. I am trying to run the calibration process to extract the lidar specific image projection model with:

`roslaunch coin_lio calibrate.launch bag_file:=<bag_path.bag> metadata_file:=<metadata_path.bag> point_topic:=<pointcloud_topic>`

But I am not understanding what is meant by:

`metadata_file:=<metadata_path.bag>`

How can I get this file?

Thank you in advance for your help.

**Comment by patripfr** [comment]
Hi!
The metadata file is provided by the ouster driver (more information can be found [here](https://github.com/ouster-lidar/ouster-ros/wiki/index). Please note that other sensors are not supported with the current codebase.

**Comment by kousheekc-lynxdrone** [comment]
I see, thanks for the clarification!
