### ISSUE TITLE
Improve image feature detection

### ISSUE THREAD

**Issue by Josgonmar** [ethz-asl/COIN-LIO#15]
Hi there!

First of all, thanks a lot for your open source contribution!
I've been trying to use your algorithm to navigate inside a long tunnel where lidar-only odometry fails.
The thing is, although it works fine in the beginning, once the UAV is deeper inside the tunnel, the number of features detected on the image is rather low, which eventually causes the odometry to drift.

![coin-lio](https://github.com/user-attachments/assets/8734b481-9fef-4c62-9dd3-291c586cf20d)

Ignoring the edges around my colleagues holding the drone (unfortunately a lot of dust was generated when the drone was flying, which also makes me wonder, have you tested it with dust?), there are almost no features detected on the image compared to the beginning of the sequence, at the entrance of the tunnel.

My question is: is there a way to increase the number of features?

Thanks in advance!

**Comment by patripfr** [comment]
Hi!
That's an interesting test case! The image looks indeed very challenging due to the "interrupted" field of view from the lidar cage and a lack of salient visual features. I have not tested with dust so far.

There are a few things you can try to get more features:
- To reduce / exclude the features on your colleagues, you can increase the [`blind`](https://github.com/ethz-asl/COIN-LIO/blob/main/config/params.yaml#L7) parameter.
- To increase the amount of detected features, you can decrease [`grad_min`](https://github.com/ethz-asl/COIN-LIO/blob/main/config/params.yaml#L50), however this might also result in more noisy/unreliable features
- Decreasing [`suppresion_radius`](https://github.com/ethz-asl/COIN-LIO/blob/main/config/params.yaml#L48) will allow features to be closer to each other in the image
- Increasing [`max_range`](https://github.com/ethz-asl/COIN-LIO/blob/main/config/params.yaml#L45) will allow features further away from the sensor
- By default the brightness filter performs some smoothing on the image. You could try to disable it by commenting [this line](https://github.com/ethz-asl/COIN-LIO/blob/main/src/image_processing.cpp#L133) to avoid blurring of subtle features, but this will also increase the noise in the image and lead to less reliable features.

**Comment by Josgonmar** [comment]
Hey, thanks for the reply!

I've followed your tips and changed the parameters accordingly, improving the overall performance. Unfortunately, I still notice some drift when the drone stops inside the tunnel (by default it would keep moving forward) and changes its yaw orientation.
These are the values that worked best for me:
- grad_min: 16.5 -> 10
- max_range: 30 -> 50
- suppression_radius: 10 -> 5
- blind: 0.65 -> 1.50

However, what I think helped more was commenting the line you suggested, which now makes the image look like this:
![coin-lio_params](https://github.com/user-attachments/assets/91aefdb1-224d-410f-a719-679eebbf4666)

It seems that the tunnel walls are too smooth in intensity to detect good features...

I also used the "mask" param to suppress features at the bottom of the image where the UAV blades and rotors are. What is the difference between the "blind" param and this mask? Are the points under the "blind" area also "masked" in the feature detection?

PD: I don't know if you're aware of this, but I ran out of memory very quickly because of the long queue the registered cloud topic had on the rviz config file.

**Comment by patripfr** [comment]
Hi,
Points in the mask are disabled by default (irrespective of their range). The "blind" parameter disables the pixels with a range lower than the "blind" value, so yes there is some overlap between these two parameters.

Yes, the default rviz config is quite memory hungry, but I chose it like this so people can recreate the same visualizations I show in the video and paper.

I think the image that you've sent looks very undesirable (it's all white in most areas). This made me realize that just commenting out the line I suggested will turn off the brightness filter completely which is not what I intended. Instead, you should replace line 133 with `img = normalized_img`. Let me know if that helps.

**Comment by Josgonmar** [comment]
Yeah, I can share both with you! Do you have an email where I can send it?
I also noticed how commenting that line would cause the same effect as setting the "brightness_filter" to false, so I was doing that instead. But i'll try replacing the line too!

**Comment by patripfr** [comment]
you can send me a link to patripfr@ethz.ch

**Comment by patripfr** [comment]
Hi,
I looked at the data and saw that the main issue for the drift you saw was features being tracked on the edge of the drone or on your colleagues. This should in theory be handled by disabling the points with a range below `blind`, however I found that for some reason those close objects also influence the intensity of valid points around them (see image below), which seems to be a shortcoming of the lidar itself.
![bleeding](https://github.com/user-attachments/assets/f25bb532-d1bd-4ee3-8ae5-497b2f8e6cfd)

To compensate this sensor problem, I added a new parameter `(erosion_margin)` to inflate the disable area around invalid points.
I do now get good performance and the sensor returns to the correct starting position without turning of the blur :)

![Screenshot from 2024-08-09 09-57-40](https://github.com/user-attachments/assets/7346c891-4585-4d4f-9eb0-2d1ae2f2592b)

I changed the following parameters:

```
preprocess:
    blind: 1.5
image:
    max_range: 40
    suppression_radius: 7
    grad_min: 9
    ncc_threshold: 0.4
    erosion_margin: 19
```

PS: I also introduced a new param (`image/blur`) that can be used to turn off the image smoothing in case you want to play around with it.

**Comment by Josgonmar** [comment]
It works great now!

I'm glad this issue has helped you improve your already awesome package :+1: 
I have one last question though, how did you come up with the idea of fusing the lidar depth image? (Doesn't the Ouster driver already publish a depth image?)
I've seen several visual-lidar-inertial odometry algorithms, but I never thought of using the same lidar to do the visual part. That's pretty smart!

Anyway, thanks for your time and effort! :100:

**Comment by patripfr** [comment]
Happy to hear I could help :)
I'm not sure what you mean by "the idea of fusing the lidar depth image". In this approach, we are using (a filtered version of) the intensity image. The ouster does indeed provide an intensity image. However, those intensity values are already processed (clipped and scaled values). For this work, I found it more useful to work with the raw information from the points directly and create the image myself. The depth image is only used to mask out certain areas and occlusions.

**Comment by Josgonmar** [comment]
Sorry, perhaps "fusing" is not the best word to describe how it works. I'm just very curious about the inspiration behind this idea of integrating LiDAR intensity images and minimizing photometric error :smile:

**Comment by patripfr** [comment]
I was looking for ways to improve LIO robustness in geometrically challenging environments and since lidar-camera fusion is a common approach to address this challenge it seemed promising to me to try a similar approach but using images created by the lidar :)

**Comment by TongxingJin** [comment]
![image](https://github.com/user-attachments/assets/54c79382-17f2-4772-8eb0-8da12b7c9c65)
Hi patripfr, thanks for your awesome work you shared.
Do you know how to explain the underlying reasons of the artefacts in the marked areas in the image? I also noticed this in some sequences in ENWIDE.

**Comment by Josgonmar** [comment]
> ![image](https://private-user-images.githubusercontent.com/79843097/362532525-54c79382-17f2-4772-8eb0-8da12b7c9c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTA5MTgsIm5iZiI6MTcyNDkxMDYxOCwicGF0aCI6Ii83OTg0MzA5Ny8zNjI1MzI1MjUtNTRjNzkzODItMTdmMi00NzcyLThlYjAtOGRhMTJiN2M5YzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA1NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjI3MmFhZjc0ODliOGRmNGU2Yjk3OGI4MWFjY2Y3YmM0NTZlYWE1MDY4NzU3YjM5MzhiMTkwYWQ3NWY1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23EQvE369CuyG1G2MxIhFXYGzclhsf2Mn1F-SA_DgYs) Hi patripfr, thanks for your awesome work you shared. Do you know how to explain the underlying reasons of the artefacts in the marked areas in the image? I also noticed this in some sequences in ENWIDE.

Hi @TongxingJin,
This is probably due to the fact that we've installed some protection around the sensor, which occludes part of the scan.

**Comment by Josgonmar** [comment]
Hey @patripfr! I hope you're doing great.

I have a few questions related to this issue, so instead of opening a new one, I'll ask them here since they're directly connected.

After seeing the great performance of your algorithm in a controlled environment, I decided to test it in a real excavation tunnel, which presents a tougher challenge. 😄 This tunnel has a relatively smooth entrance, approximately 100 meters long. Standard lidar-inertial algorithms struggle in this section due to the similar geometric characteristics, but your approach should be able to handle it well.

However, there's a challenge: the entrance is covered in what appears to be charcoal or a similar material, making it completely black and smooth. As a result, the intensity of the returned lidar points is quite low, producing an intensity image like this:

![Image](https://github.com/user-attachments/assets/208a0059-2ad7-4476-a373-fd3e44fffcd9)

As you can see, the image not only lacks distinct features but also appears very noisy at longer distances. This is causing issues with the algorithm's performance in this section. Once past this area, the image quality improves slightly:

![Image](https://github.com/user-attachments/assets/b512d278-1ac0-4171-9c3c-206b93a7878e)
![Image](https://github.com/user-attachments/assets/51a6e13f-0f33-44e3-8db9-e7e4cfa2f481)

Although there is less noise on the sides, the front view still remains quite noisy. I have tested deactivating the brightness filter and using reflectivity values, which reduces some noise, but there still aren’t enough robust features to maintain proper tracking. This results in odometry staying still when it should be moving forward:
![Image](https://github.com/user-attachments/assets/fd1cf539-17b1-49b7-8800-ad544f8c0720)

Once past this difficult section, the algorithm resumes the expected behaviour:
![Image](https://github.com/user-attachments/assets/35d6ae5d-3877-4c01-abed-a2df49ce7aa1)
However, now some parts of the image are too bright.

Here is the configuration I’m currently using:

- line_removal: true
- brightness_filter: false
- blur: true
- reflectivity: true
- patch_size: 5
- max_range: 30
- max_lifetime: 25
- min_range: 0.7
- suppression_radius: 10
- num_features: 60
- grad_min: 16.5
- ncc_threshold: 0.7075
- margin: 10
- intensity_scale: 0.25
- window: [41, 7]
- masks: [0, 95, 1023, 32, 90, 0, 100, 90, 334, 0, 100, 90, 595, 0, 100, 90, 840, 0, 100, 90]
- erosion_margin: 19

Do you think there's a way to improve the filtering to make the images less noisy, or is this just an inherent limitation of the environment? I could bypass this problematic entrance entirely, but I’d like to try everything possible before doing that.

Thanks a lot in advance!

**Comment by patripfr** [comment]
Hi @Josgonmar, 
I agree, this environment looks very challenging, both geometrically and visually. It seems that there's also some sort of cage around the LiDAR, which doesn't make things easier. I don't have an immediate idea what could be changed to improve performance, as the images look very featureless, but I'd be happy to play around myself if you could share a rosbag.

**Comment by Josgonmar** [comment]
Hey @patripfr, sorry for the late reply!

I'm not entirely sure if I can share the rosbag data with you, as the tests were conducted in a private facility. However, I'll check and should have a definitive answer by next week. Is [patripfr@ethz.ch](mailto:patripfr@ethz.ch) still your contact email?

To make things feasible, we ended up clearing the walls a bit, though it was still quite a challenge. Also, the lidar cage has to stay in place unfortunately, but I doubt it would offer much protection if crashing 😆.

By the way, I noticed something interesting during all flights: at some point, the Z-axis estimation would drop below 0 after a few hundred meters deep, even though the tunnel is supposed to be completely flat. Do you have any idea why this might be happening? Could it be due to a poor IMU initialization?

Cheers!

**Comment by patripfr** [comment]
Yes, that's my contact email. 
Regarding the Z-axis: FAST-LIO2 (and therefore also COIN-LIO, as it is built on top) does not estimate poses in a gravity aligned reference frame (also see [here](https://github.com/hku-mars/FAST_LIO/issues/266)), but with respect to the first IMU pose. In reality, the sensor is typically not perfectly aligned with gravity, which then results in a coordinate system with a slight offset compared to gravity. Especially at larger distances this "misalignment" is noticeable then due to the lever arm effect.
