### ISSUE TITLE
Inquiry about a potential enhancement with a loop closure detector

### ISSUE THREAD

**Issue by ouazmourad** [ethz-asl/COIN-LIO#16]
Hey Patrick, 

Again thank you for the work put into your framework. This is not an issue rather than an open question, I wanted to ask if you are considering adding a loop closure detector to the framework, and if not, which algorithm of the many existing SLAM frameworks do you think would be the most compatible with COIN-LIO? Thanks in advance.

**Comment by patripfr** [comment]
Hi,
I am currently not planning to add a loop-closure capability to the framework. The kalman-filter-based framework that COIN-LIO is built upon (FAST-LIO2 / IKFOM) is not very compatible with loop-closures by itself. However, there are several open-sourced projects that combined FAST-LIO2 with a factor-graph to make it loop-closure compatible:

https://github.com/yanliang-wang/FAST_LIO_LC
https://github.com/gisbi-kim/FAST_LIO_SLAM

COIN-LIO could be integrated there in a similar way. Additionally, there are also works that leverage the intensity images for loop-closure detection, which would be a logical fit for COIN-LIO:
https://github.com/TixiaoShan/imaging_lidar_place_recognition
