### ISSUE TITLE
The ENWIDE LiDAR Inertial Dataset could not be downloaded

### ISSUE THREAD

**Issue by BetterYimi** [ethz-asl/COIN-LIO#19]
Thank you for your excellent work, but your dataset website does not appear to be working and http://robotics.ethz.ch/~asl-datasets/2024_ICRA_ENWIDE is inaccessible.

**Comment by patripfr** [comment]
Hi,
thanks for the interest in our dataset and for bringing this up. The dataset server of our lab seems to be down at the moment and we're working on fixing it.

**Comment by patripfr** [comment]
FYI: The server is up and running again

**Comment by BetterYimi** [comment]
> FYI: The server is up and running again
Thanks for your reply.
