### ISSUE TITLE
Problem with build 

### ISSUE THREAD

**Issue by hello299** [ethz-asl/COIN-LIO#21]
Hello ,I follow the command followed:
in my workspace: 
catkin init 
catkin config --extend /opt/ros/$ros_distro
catkin config --cmake-args -DCMAKE_BUILD_TYPE==RelWithDebInfo
 and  I don't follow the command catkin config --merge-devel
 and finally use:
catkin build coin_lio --force_cmake instead and I got successed finished.
![2024-10-10 10-24-59 的屏幕截图](https://github.com/user-attachments/assets/5675292a-30d2-477c-85d5-376db4a98841)

**Comment by hello299** [comment]
![2024-10-10 10-24-59 的屏幕截图](https://github.com/user-attachments/assets/ebee30df-88d0-47be-9e6a-1054fa1a01aa)

**Comment by Chaoyue-cpu** [comment]
Hi，thank you very much
