### ISSUE TITLE
Strange intensity image on OS0-128 Rev6 Sensor with latest firmware and ros driver

### ISSUE THREAD

**Issue by zzxxtt** [ethz-asl/COIN-LIO#22]
Hello, Thank you for your great project. 
I use the OS0-128 Rev6 Sensor with latest firmware (v2.5.3) and latest ros driver (0.13.1)
When running my own dataset, I found that the intensity image seems have some error, I'm not sure how it is cause. In ouster driver rviz it looks correct. The following image is the compare of two intensity image.
![compare](https://github.com/user-attachments/assets/074291e9-23c4-421f-98f5-6e2d68e27b88)
I try to run the calibrate, the result is 0. And I also try both 1024x10 mode and 2048x10 mode, none of them seems correct.

The problem is because the destaggered point clouds feature introduces in ouster-ros driver 0.10.0, After 0.13.0 driver there's a new parameter destagger in launch file which can be set the false, can solve this issue

**Comment by patripfr** [comment]
Thanks for letting me know! Is the parameter that sets the destaggering included in the json? If so, I'll try to update the codebase to consider this.

**Comment by zzxxtt** [comment]
No, that parameter is in the launch file of latest ouster-ros.   like <arg name="destagger" default="true"    doc="enable or disable point cloud destaggering"/>

**Comment by patripfr** [comment]
That's very unlucky. I'll try to see if I can add a flag to also accommodate destaggered clouds in the future.

**Comment by TongxingJin** [comment]
So, dose that mean in the new version of Ouster driver, the points sampled in the same yaw angle have been placed in the same column rather than the same sampling timestamp?

**Comment by patripfr** [comment]
Yes, I think so
