### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by peter-ivarsen** [ethz-asl/COIN-LIO#26]
Hi, 

i get an error when trying to build the latest commit: 
```
COIN_LIO_ws/src/COIN-LIO/include/common_lib.h:3:10: fatal error: coin_lio/Pose6D.h: No such file or directory
    3 | #include <coin_lio/Pose6D.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
But builds fine when I check out the previus commit  e46ca6a1ef17f9ba8af4efd4faaa567d86a11b36

cheers

**Comment by patripfr** [comment]
Hi Peter,
I'm not sure why this is happening for you, as nothing has changed about this file or the include of this file since the commit that you mentioned (check: https://github.com/ethz-asl/COIN-LIO/compare/e46ca6a...main).
Glad to hear you could solve it by using the previous commit :)
