### ISSUE TITLE
Support for other Livox lidar series

### ISSUE THREAD

**Issue by 85256638** [ethz-asl/COIN-LIO#28]
Thanks for open-sourcing this great piece of work. May I know whether COIN-LIO work with LIVOX Horizon/Avia lidars?
I know someone has asked whether MID-360 is supported or not, and the answer is no.

**Comment by patripfr** [comment]
Hi,
Unfortunately, due to the irregular scan pattern of Livox lidars, they are not suitable for COIN-LIO.
