### ISSUE TITLE
Velodyne16 

### ISSUE THREAD

**Issue by binbin2002** [ethz-asl/COIN-LIO#29]
Thanks for open-sourcing this great piece of work. May I know whether COIN-LIO work with Velodyne?

**Comment by patripfr** [comment]
Hi,
as COIN-LIO creates images by projecting the lidar beams, a 16-beam lidar would result in an image with 16px height, which unfortunately isn't very useful for feature tracking and COIN-LIO is therefore not suitable for a 16-beam velodyne lidar.
