### ISSUE TITLE
About LIVOX Mid-360

### ISSUE THREAD

**Issue by liupandede** [ethz-asl/COIN-LIO#6]
Thanks for this great work in the SLAM LIO research field!
May I ask if it is possible for this work to support Mid-360? If not, how can I modify the code to use it on Mid-360.

**Comment by patripfr** [comment]
Hi,
Thanks for your interest. Unfortunately, COIN-LIO can only operate with LiDARs that have a regular scan pattern, which enables the creation of a dense image. Unfortunately, this is not possible with a Mid-360 and substantial changes in the algorithm would be required to support sparse images.
