### ISSUE TITLE
drift on tunnel dataset

### ISSUE THREAD

**Issue by TongxingJin** [ethz-asl/COIN-LIO#8]
Hi, thanks for your inspiring work and opensource code.
I have tried on 2023-08-08-17-12-37-tunnel_s.bag with default parameters in mapping_enwide.launch, but the odometry drift a lot in the tunnel direction like this,
![rviz_screenshot_2024_06_11-14_11_02](https://github.com/ethz-asl/COIN-LIO/assets/79843097/12afee62-b67c-4753-aa48-edd1622cb2a6)
So what do you think is the reason, and how can I do to get the performance like you did? Thanks.

**Comment by patripfr** [comment]
Hi,
I'm not sure what happened in your case, I've just ran it on my machine without any issues to double check.
![tunnel_s](https://github.com/ethz-asl/COIN-LIO/assets/28986714/db231bac-d72c-4fb6-9f03-ec3df8b66390)

One potential issue I could imagine is that your machine cannot keep up with playing the bag in realtime (especially when you are running rviz in parallel) and starts dropping frames. 

Could you try running the bag with a slower replay speed and turning of rviz?

**Comment by TongxingJin** [comment]
Hi, thanks for your prompt reply. I solved this problem by rebooting my PC, maybe it's the excessive usage of memory that lowered the processing frequency.
And one suggestion is you could publish downsampled points in /cloud_registered_body to avoid the unnecessary burden of rviz and memory usage.
My outcome now looks like this, so the little drift on the wall is normal performance, right?
![rviz_screenshot_2024_06_11-18_24_08](https://github.com/ethz-asl/COIN-LIO/assets/79843097/dea3dcda-f511-4b23-ab79-a56930abff77)

**Comment by patripfr** [comment]
Great to hear :) Yes, this is the expected performance. 
Thanks for the suggestion, so far I publish the full cloud for a better visualization of the intensity in the environment, but indeed this is very heavy in memory and for rviz. I might add an option for downsampling in a future version.

**Comment by TongxingJin** [comment]
You could use pcl::UniformSampling to replace pcl::VoxelGrid to implement downsampling and meanwhile avoid the unwanted averaging of intensity, it works for me.
